### ISSUE TITLE
Findings,  observations, comments

### ISSUE THREAD

**Issue by moinmoin-sh** [OXRS-IO/OXRS-IO-DigitalIO-ESP-FW#1]
I gave the DigitalIO FW a play.
The `pinType `dependent config menue looks nice and intuitive

- You configure an output as `HIGH `active. I intentionally configure outputs `LOW `active as documented (Thats was the build flags were for.) I wanted input and outputs having the same safe state as inactive.
- I'm not able to set outputs, neither via `MQTT `nor via `Command `from the Admin UI.
- T looks like you changed the API from "index" to "gpio", I wanted to stay with the standard UI.
- I think the config payload has also changed, at least the `gpio type` (input / output) has to be included. 
- The API changes lead to several changes in the documentation - it's not like StateMonitor/StateController any more

**Comment by sumnerboy12** [comment]
Thanks Moin; comments below;

* Whoops, this was missed when I moved it across. I can see your point, but I was trying to keep consistent with the State Controller output state. I will revert to your intention however, `LOW` active.
* This was a bug, should be resolved shortly
* Yes, as discussed on Discord - I think it is worth have the correct descriptive name for this field, any downstream processing logic usually only considers `type` and `event` in the payload, upstream filtering is done on `index` or `gpio`, so existing business logic shouldn't be adversely affected
* Yes, the config payload has to change, to allow both input and output configuration of a single pin. There is a nested `input` and `output` object in the config payload which mirrors the State Monitor/Controller config payload, it just needs to be wrapped with `gpio` and `type` (`input` or `output`)
* Yes, it is on my TODO to fix that up

**Comment by moinmoin-sh** [comment]
Looks good now!
